### ISSUE TITLE
진수원 중식 식단 평가 및 예외처리

### ISSUE THREAD

**Issue by qivvoon** [su-mmer/JBNU_OSS_PROJECT#20]
* 평가는 3단계로 구현한다.
* 평가점수는 최대가 3점, 최하가 1점이다.
* 특정단어가 식단에 있다면 +1점 또는 -1점을 해준다. 
* 토요일, 일요일의 경우 예외처리 후 안내메시지를 보낸다.

**Comment by su-mmer** [comment]
머지 완료
