### ISSUE TITLE
[BUG] mocha test token error

### ISSUE THREAD

**Issue by qivvoon** [su-mmer/JBNU_OSS_PROJECT#49]
# 🐞버그 설명
gitHub action으로 mocha test실행 시, test.spec.js가 토큰을 가져오지 못해 오류가 발생하였다.

## 🐞발생 상황
mocha test를 위해선 토큰이 필요하지만, gitHub에는 토큰이 올라가 있지 않다. 
따라서, gitHub action으로 mocha test실행 시 오류가 발생하였다.

## 🐞예상 동작
js파일을 push할 시, gitHub action의 mocha test가 token에러 없이 정상적으로 실행된다.

## 버그 해결 방안
- 토큰 관련 에러 발생 시, 바로 종료 시킨다.
- gitHub secret을 사용해 mocha test시 gitHub action에서 토큰을 이용할 수 있도록 해준다. 

# 🐞사용한 기기
 - [x] **Desktop (please complete the following information):**
 - Window

 - [ ] **Smartphone (please complete the following information):**

**Comment by su-mmer** [comment]
토큰 에러 머지 완료
